### PR TITLE
Allow trying multiple sources

### PR DESCRIPTION
**Pull request by ahstro**
Okay, this is it. I've tested it, I've used it in production, it should be fine, "infinite loop"-free, and all sorts of awesome. Fingers crossed :four_leaf_clover:

### CODE REVIEW

**Comment by conorhastings** [comment]
hey @ahstro i've implemented some tests for this component recently. Would you mind checking them out and seeing if you can add some for the new functionality. Thanks! I'd be happy to help if you have any questions.

**Comment by ahstro** [comment]
Ah, of course. :)

**Comment by mattaningram** [comment]
Hey @conorhastings @ahstro is this what is preventing the fallback array from working? It says in your docs you can pass an array of fallback images, but that doesn't seem to work and this pull request appears to be related?

**Comment by conorhastings** [comment]
@mattaningram guessing the documentation never got updated when the original PR got reverted. I can try to work this into a new release, I'll update the documentation now to reflect that this is not currently a feature.

**Pull request closed without merging**
