### PR TITLE
Patch bad DOM: <img fallbackImage= ...>

### PR DESCRIPTION
**Pull request by mheiber**

### CODE REVIEW

**Comment by conorhastings** [comment]
@mheiber do you have a reproducable case? this shouldn't be happening in any current version of react.

Something similar to this should go in at some point but I need to think more about whether or not we want to be more aggressive than this

**Comment by mheiber** [comment]
@conorhastings thanks for following up. I can send a screenshot tomorrow, and this isn't a blocker.

**Comment by conorhastings** [comment]
@mheiber thanks, no rush, running code would be preferable if possible, you can use https://esnextb.in/ with gists to access es6 imports etc...

**Comment by mheiber** [comment]
@conorhastings here's an example.

Source code:

screen shot 2016-08-08 at 9 23 05 am

Warning message in the console:

screen shot 2016-08-08 at 9 21 43 am


React dev tools:

screen shot 2016-08-08 at 9 22 13 am

**Comment by conorhastings** [comment]
@mheiber coool cool, what I would expect, doesn't appear to be getting into the actual dom just the virtual dom

**Comment by mheiber** [comment]
relevant React issues:

https://github.com/facebook/react/pull/6800
https://github.com/facebook/react/issues/7152

**Comment by conorhastings** [comment]
@mheiber yup I'm aware of the react issue

**Comment by julienben** [comment]
@conorhastings Why do we need to pass fallbackImage and initialImage to the ?

Why not just the following?

return this.state.imageSource ?  : null;

Your solution shows the same "unknown DOM property" warnings for me.

**Comment by mheiber** [comment]
I'm thinking (based on discussion in the React issue) that `delete`ing the keys is better than assigning `null`.

**Comment by conorhastings** [comment]
@mheiber delete isn't ideal as it's very slow- https://www.smashingmagazine.com/2012/11/writing-fast-memory-efficient-javascript/

**Comment by mheiber** [comment]
@conorhastings that's why I want to avoid `delete`, but there doesn't seem to be a good option. On the React issue, people recommended explicitly assigning all properties we want, but `` actually has a TON of HTML attributes and it would be crazy to assign them all.

**Comment by conorhastings** [comment]
@mheiber I think the warning makes sense, as in order to properly support web components they need to make all props pass through to the DOM. It follows the long term react pattern of giving warnings for breaking changes before breaking things, and only appears in development and not production which is relatively pragmatic.

Currently the whitelist react is using is also relatively unmaintainable as html properties change.  

I'd prefer not to go with delete so I'm going to mull over other other potential options before deciding what to do here.

**Comment by conorhastings** [comment]
@mheiber I think I'm going to go with this solution https://github.com/socialtables/react-image-fallback/pull/30/files as it will also prevent props that are spread in by consumers of the module and not just ones this component is directly responsible for.

**Comment by mheiber** [comment]
@conorhastings nice solution. I like the use of the html-attributes module much better than listing out all the possible attributes for an `` tag.

**Pull request closed without merging**
