### PR TITLE
upgrade to react 0.14, change dependency to peerDependency

### PR DESCRIPTION
**Pull request by conorhastings**
xref https://github.com/socialtables/venue-mapper/issues/964

### CODE REVIEW

**Comment by conorhastings** [comment]
cc @fortruce and @jjow , can one of you take a look at this.

**Comment by rickyvetter** [comment]
Interesting strategy with the <15... just guessing that it may break?

**Comment by tiansijie** [comment]
@rickyvetter are you working on 0.15?

**Comment by conorhastings** [comment]
@rickyvetter yeah, don't imagine this will break, but just being safe I suppose.

**Comment by rickyvetter** [comment]
It's an interesting trade off - things possible breaking in 0.15 vs things maybe not breaking and everyone having to wait on the lib. Dependencies suck :(

**Comment by rickyvetter** [comment]
@tiansijie nope.

**Comment by conorhastings** [comment]
@rickyvetter they really really do...would be interesting if there were tests...to check for updates of peerDepdencies every so often and try to do some sort of automated PR with version bump and see if tests pass...would be an explicit reminder even if there is failure for maintainer to look into it...hmm...i wonder if i like this idea.

**Comment by conorhastings** [comment]
even without tests if the PR was automated that would be interesting.

**Comment by rickyvetter** [comment]
haha that sounds like a pretty complex solution. id rather everyone just use semver.

**Comment by conorhastings** [comment]
hahaha, yes yes semver is still part of this, i just don't want to have to remember to upgrade all my modules.

**Comment by rickyvetter** [comment]
yeah - i suppose that doesn't solve all of it. we really need npm to just understand what broke and do automatic code mods to fix everything in the dependency tree.

**Comment by conorhastings** [comment]
codemods wowowow....you really do work at facebook. but yes that would be very nice :p

**Pull request merged**
