### PR TITLE
Remove unnecessary span tag from output

### LINKED ISSUE #12: Remove or add class to <span>
If people have styled `span` tags where using `react-image-fallback`, there's currently no simple way to unstyle the `span` surrounding the `img`.
I would suggest removing it or, if there's a good reason for it being there, add a class to it, so that it can easily be unstyled with CSS.
I would've made a PR, but I wanted to discuss which alternative is better first.

### PR DESCRIPTION
**Pull request by ahstro**
Closes #12

### CODE REVIEW

**Comment by conorhastings** [comment]
looks good to me, thanks for the contribution

**Comment by ahstro** [comment]
Thank you for the component :)

**Comment by conorhastings** [comment]
@ahstro published as `v2.0.0`

**Comment by ahstro** [comment]
Awesome, thanks :)

**Pull request merged**
